### ISSUE TITLE
MQTT problem

### ISSUE THREAD

**Issue by pointlevel** [Pythm/ad-Lightwand#3]
Hi,

Im not getting the mqtt to work. My setup is latest HA with zigbee2mqtt-addon. When i connect to mqtt through the mqtt-explorer i have to include the password and username for my HA user, can that be the problem?

```yaml
MQTTLights:
  - lights:
      - zigbee2mqtt/Livingroom Window 1
    automations:
      - time: "07:00:00"
```

```
2024-11-02 08:32:30.668784 WARNING Livingroom: ------------------------------------------------------------
2024-11-02 08:32:30.669081 WARNING Livingroom: Unexpected error running initialize() for Livingroom
2024-11-02 08:32:30.669307 WARNING Livingroom: ------------------------------------------------------------
2024-11-02 08:32:30.670621 WARNING Livingroom: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/apps/lightwand.py", line 186, in initialize
    light = MQTTLights(self,
            ^^^^^^^^^^^^^^^^
  File "/config/apps/lightwand.py", line 1685, in __init__
    self.mqtt.mqtt_subscribe(light_topic)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'mqtt_subscribe'

2024-11-02 08:32:30.670888 WARNING Livingroom: ------------------------------------------------------------
```

**Comment by Pythm** [comment]
If you are running zigbee2mqtt inside HA as addon there is probably no advantages to my knowledge to call mqtt since the calls would go thru HA anyway. Addons is a bit unfamiliar territory for me so I might be wrong.

NoneType is probably because there is no light at "zigbee2mqtt/Livingroom Window 1". Have you configured MQTT in appdaemon?

If you are running Appdaemon as a addon there might be some documentation in HA on how to set up MQTT. Or check Appdaemon documentation: [https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#mqtt](https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#mqtt)

**Comment by pointlevel** [comment]
Of course, my bad. MQTT wasn´t configured in Appdaemon, thanks.
